version: '3'

services:
  nginx:
    image: nginx:mainline-alpine3.18-slim
    container_name: sa-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: sa-php83
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
###> symfony/mailer ###
  mailer:
    image: axllent/mailpit:latest
    container_name: sa-mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
