version: '3'

services:
  nginx:
    image: nginx:mainline-alpine3.18-slim
    container_name: sa-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: sa-php83
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    depends_on:
      - database
      - rabbitmq
###> symfony/mailer ###
  mailer:
    image: axllent/mailpit:latest
    container_name: sa-mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine3.18
    container_name: sa-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app-pwd}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: sa-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./var/rabbitmq/data/:/var/lib/rabbitmq/
      - ./var/rabbitmq/log/:/var/log/rabbitmq

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
