services:
  nginx:
    image: nginx:mainline-alpine-slim
    container_name: sa-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: sa-php84
    ports:
      - "9000:9000"
    environment:
      APP_ENV: ${APP_ENV:-dev} # Добавлено для явного указания окружения
    volumes:
      - ./:/var/www
    depends_on:
      - database
      - rabbitmq
      - redis

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit:latest
    container_name: sa-mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    restart: unless-stopped # Добавлено для автоматического перезапуска
  ###< symfony/mailer ###

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    container_name: sa-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-app-pwd}
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    restart: unless-stopped # Добавлено для автоматического перезапуска
  ###< doctrine/doctrine-bundle ###

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: sa-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-app}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-app-pwd}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    restart: unless-stopped # Добавлено для автоматического перезапуска

  redis:
    image: redis:alpine
    container_name: sa-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      REDIS_PASS: ${REDIS_PASS:-redis-pwd}
    command: ["redis-server", "--requirepass", "${REDIS_PASS}", "--appendonly", "no", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - redis_data:/var/lib/redis
    restart: unless-stopped # Добавлено для автоматического перезапуска

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
  rabbitmq_data:
  rabbitmq_logs:
  redis_data:
